name: CD Demo
on:
  push:
    branches:
      - test-cd
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node
      uses: actions/setup-node@master
    # 使用GitHub的Secrets来存储私钥内容，然后在执行时再创建私钥文件。
    - name: Generate provate key
      run: echo "$UPLOAD_PRIVATE_KEY" > private.key
      env:
        UPLOAD_PRIVATE_KEY: ${{ secrets.UPLOAD_PRIVATE_KEY }}

    - name: Change ENV
      if: github.head.ref == 'test-cd'
      run: sed -i '' "s/\'test\'/\'prod\'/g" utils/config.js

    - name: Build an Deploy
      run: |
        npx yarn
        node ci.js --pkp=./private.key
